# Generated by Django 4.2.4 on 2023-08-29 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppCoder', '0009_remove_entregable_estudiante'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estudiante',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
    ]
